// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9RtsXMRPeD5vpORJcWLDb1lEJZ3nUWI',
    appId: '1:892472148061:web:f22a5c4ffd25858726cdb4',
    messagingSenderId: '892472148061',
    projectId: 'xonapp',
    authDomain: 'xonapp.firebaseapp.com',
    databaseURL:
        'https://xonapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'xonapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8vcumpnJICxh7XZ3jKPcncrDvLg8NtA',
    appId: '1:892472148061:android:d9c3f2b749219e9e26cdb4',
    messagingSenderId: '892472148061',
    projectId: 'xonapp',
    databaseURL:
        'https://xonapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'xonapp.appspot.com',
  );

  // Secondary Firebase project for Storage only
  static const FirebaseOptions storageProjectWeb = FirebaseOptions(
    apiKey: 'AIzaSyCvhWDQOm7zeMc_JRFObRaNtwCzpGTn1s8',
    appId: '1:948742284303:web:8c2c69f5c676a9fa5daf7a',
    messagingSenderId: '948742284303',
    projectId: 'quanlybd-2eb5e',
    authDomain: 'quanlybd-2eb5e.firebaseapp.com',
    databaseURL:
        'https://quanlybd-2eb5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlybd-2eb5e.appspot.com',
    measurementId: 'G-EYSDGDFS60',
  );

  static const FirebaseOptions storageProjectAndroid = FirebaseOptions(
    apiKey: 'AIzaSyCvhWDQOm7zeMc_JRFObRaNtwCzpGTn1s8',
    appId: '1:948742284303:android:PLACEHOLDER',
    messagingSenderId: '948742284303',
    projectId: 'quanlybd-2eb5e',
    databaseURL:
        'https://quanlybd-2eb5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlybd-2eb5e.appspot.com',
  );

  static FirebaseOptions get storageProject {
    if (kIsWeb) {
      return storageProjectWeb;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return storageProjectAndroid;
      default:
        return storageProjectWeb;
    }
  }
}
